---

- name: Check existence of qBittorrent systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ qbittorrent_identifier }}.service"
  register: qbittorrent_service_stat

- name: Uninstall qBittorrent systemd services and files
  when: qbittorrent_service_stat.stat.exists | bool
  block:
    - name: Ensure qBittorrent systemd service is stopped
      ansible.builtin.service:
        name: "{{ qbittorrent_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure qBittorrent systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ qbittorrent_identifier }}.service"
        state: absent

    - name: Ensure qBittorrent path doesn't exist
      ansible.builtin.file:
        path: "{{ qbittorrent_base_path }}"
        state: absent
